"""
A dictionary that converts mnemonics to explanations of what opcodes do.
"""

explained = {'ADD': 'Add A to B and store in Z',
 'CMP': 'Compare A and B (subtract but only set flags)',
 'CSB': 'Go to subroutine',
 'DCA': 'Decrement A',
 'DCB': 'Decrement B',
 'DCQ': 'Decrement !',
 'DCX': 'Decrement X',
 'DCY': 'Decrement Y',
 'DCZ': 'Decrement Z',
 'INA': 'Increment A',
 'INB': 'Increment B',
 'INQ': 'Increment C',
 'INX': 'Increment X',
 'INY': 'Increment Y',
 'INZ': 'Increment Z',
 'JC': 'Jump if Carry',
 'JMP': 'Jump',
 'JNC': 'Jump if no Carry',
 'JNZ': 'Jump if not Zero',
 'JZ': 'Jump if Zero',
 'LAIQ': 'Load A indirect with Q',
 'LBIQ': 'Load B indirect with Q',
 'LDA': 'Load A',
 'LDB': 'Load B',
 'LDX': 'Load X',
 'LDY': 'Load Y',
 'LSH': 'Left shift A and store to Z',
 'LXIQ': 'Load X indirect with Q',
 'LYIQ': 'Load Y indirect with Q',
 'NOP': 'No Operation',
 'RSB': 'Return from subroutine',
 'RSH': 'Right shift A and store in z',
 'STA': 'Store A to memory location',
 'STAI': 'Store A indirect with Q',
 'STB': 'Store B to memory location',
 'STBI': 'Store B indirect with Q',
 'STX': 'Store X',
 'STXI': 'Store X indirect with Q',
 'STY': 'Store Y',
 'STYI': 'Store Y indirect with Q',
 'STZ': 'Store Z',
 'STZI': 'Store Z indirect with Q',
 'SUB': 'Subtract B from A and store in Z',
 'TAB': 'Transfer A to B',
 'TAQ': 'Transfer A to Q',
 'TAX': 'Transfer A to X',
 'TAY': 'Transfer A to Y',
 'TBA': 'Transfer B to A',
 'TBQ': 'Transfer B to Q',
 'TBX': 'Transfer B to X',
 'TBY': 'Transfer B to Y',
 'TQA': 'Transfer Q to A',
 'TQB': 'Transfer Q to B',
 'TQX': 'Transfer Q to X',
 'TQY': 'Transfer Q to Y',
 'TQZ': 'Transfer Q to Z',
 'TXA': 'Transfer X to A',
 'TXQ': 'Transfer X to Q',
 'TXY': 'Transfer X to Y',
 'TYA': 'Transfer Y to A',
 'TYQ': 'Transfer Y to Q',
 'TYX': 'Transfer Y to X',
 'TZA': 'Transfer Z to A',
 'TZQ': 'Transfer Z to Q',
 'TZX': 'Transfer Z to X',
 'TZY': 'Transfer Z to Y'}